### ISSUE TITLE
Type Problems

### ISSUE THREAD

**Issue by alexzakarov** [jacsmith21/gnn#1]
Hello, I guess you changed your nick on github and because of it there exists type problems here. For example, in mat package, trying to get "github.com/jacsmith21/gnn/vec" package but your base at "github.com/jsmith/gnn/vec".

If you want I can help you to resolve this kind of problems and to "develop the gnn package.

**Comment by jsmith** [comment]
Hi @alexzakarov, yes I changed that a while ago! If you want to help resolve the issues, I'd be happy to approve any PRs!

**Comment by alexzakarov** [comment]
Thank you for your quick return. I think that will be great !
